### ISSUE TITLE
Add instructions about how to create a Ledger wallet with GUI

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/monero-GUI-guide#107]
https://monero.stackexchange.com/questions/9901/how-do-i-generate-a-ledger-monero-wallet-with-the-gui-monero-wallet-gui

**Comment by el00ruobuob** [comment]
Isn't it already done by linking to it in ch02.md? Or do you want those instructions to be written down here?

**Comment by erciccione** [comment]
I consider this resolved :)
