### ISSUE TITLE
Intra-links not consistent

### ISSUE THREAD

**Issue by el00ruobuob** [monero-ecosystem/monero-GUI-guide#120]
The intra-links are not consistent (broken) as far as i can see.  
Links refers to numbered sections, while the section are unnumbered.  

Let's look at line 90 of chapter 02 in #116: `[2.1.1](#211-add-a-password)`  
While the referring heading is: `### Add a password`.

Either the link should be: `[2.1.1](#add-a-password)`, but why even display it as `2.1.1` then?  
Or the heading should be: `### 2.1.1. Add a password`.

The Question is: would we like to use numbering in chapter or not?  
An advantage of chapter numbering is to prevent collision in case two different heading are named the same.

**Comment by erciccione** [comment]
Those are a leftover from when we used numbers, i forgot to fix them. We decided to switch to a non-numbered list when the template was created, i can't find the issue/PR now. I think the current non-numbered system works weel, but if you think we should switch back we can discuss about it.

**Comment by el00ruobuob** [comment]
I'm fine with unumbered list, then I will update my first PR to correct the links.  
Thanks!

**Comment by erciccione** [comment]
This is resolved
