### ISSUE TITLE
Download of new version 0.15.0.4-Carbon Chamaeleon

### ISSUE THREAD

**Issue by Fenix2013** [monero-ecosystem/monero-GUI-guide#158]
Yesterday I downloaded, verified the signature, hashes and binary codes and then installed the latest version of Monero GUI Wallet 0.15.0.4-Carbon Chamaeleon(I use Windows 10 Home version 1909).But after successful installation, I can't run the application, it doesn't work, I can't open it. I checked all files, everything is fine installed (e.g. monerod, monero-daemon, etc.), I also checked my antivirus program to see if it accidentally blocked something (firewall, quarantine, virus chest, etc.), but everything is fine, but I still can't open the wallet and it doesn't ot work. Previously, I was using version 0.15.0.2-Carbon Chamaeleon and it worked normally with no problems with it (I use it at a local node). I tried to reinstall it and it works fine, but when I reinstall 0.15.0.4, it doesn't work again. Please, can anyone tell me where or what is the problem?
Thank you

**Comment by erciccione** [comment]
I missed this before. If you haven't solved yur problem try asking on #monero on IRC or /r/monerosupport on reddit.

**Comment by Fenix2013** [comment]
Hi,
yes I have solved my problem,but thank you for your attention.

Kindest regards


Dňa ut 7. 4. 2020, 15:04 erciccione <notifications@github.com> napísal(a):
