### ISSUE TITLE
Ledger Nano S no longer works with 0.17.1 version

### ISSUE THREAD

**Issue by SteffenIvanhoe** [monero-ecosystem/monero-GUI-guide#192]
After installation of 0.17.1 I can no longer open my Ledger Nano S Monero account. I get the error message 

  Couldn't open wallet: Wrong Device Status: 0x6e00
  (SW_CLA_NOT_SUPPORTED), EXPECTED 0x9000
  (SW_OK), Mask 0xffff

BTW: Where can I find the previous version 0.16.x to restore wallet access?

**Comment by erciccione** [comment]
Hello. This is the repository of the guide for the GUI wallet. For info about the GUI itself, take a look at https://github.com/monero-project/monero-gui
