### ISSUE TITLE
Problem on daemon synchronization for the downloaded local node

### ISSUE THREAD

**Issue by Lostsite** [monero-ecosystem/monero-GUI-guide#198]
Wallet virsion: 0.17.1.9-3ca5f10f (Qt 5.15.2)/0.17.1.9-release

What did I do: Because I do not have enough space on my local hard drive, so I downloaded the local node to my personal NAS.

What happened: After I start the wallet it takes forever to scan and load my local node (like take 1 hour to load 1%, and it only take like 10 hours to download (after I pruned)). And the link with my NAS to my PC is reliable and high speed (1000Mbps dock wired).

**Comment by erciccione** [comment]
This is the repository for the guide included in the GUI wallet. For support about the GUI, please got to /r/monerosupport on reddit or #monero on IRC or matrix.
