### ISSUE TITLE
exchange "loading" freeze

### ISSUE THREAD

**Issue by zdeneksofr** [monero-ecosystem/monero-GUI-guide#199]
Dears
I've tried to exchange about 0.5 XMR to BTC, filled amount + valid BTC address. new window Exchange says "loading" in Remaining XMR payble AMOUNT + BTC to be paid out AMOUNT
it's about "hours" to freeze on this screen. After few hours I'm able to start exchange again, but with the same result

latest Mac OS, app is in mode "download automaticky SW updates", so should be tha latest

thanks, Zdeněk

**Comment by erciccione** [comment]
This is the repository for the guide included in the GUI wallet. For support about the GUI, please got to /r/monerosupport on reddit or #monero on IRC or matrix.
