### ISSUE TITLE
Pandoc integration

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/monero-GUI-guide#23]
as suggested [here](https://github.com/monero-ecosystem/monero-GUI-guide/issues/22#issuecomment-385525305).

**Comment by erciccione** [comment]
@pazos how heavily should the document be reformatted?

**Comment by pazos** [comment]
to be parseable we need to use relative path for images (eg: replace /media/image.png for media/image.png). But using a template can benefit us in the long run. In that case I would go for using https://github.com/evangoer/pandoc-ebook-template, which has rules to build epub, pdf and html. If you are ok with that template I can submit a PR.

In the long run we can look at generating jeckyll static pages with pandoc too, but I think isn't needed for now.

@erciccione: do you use mac/linux as your OS? I'm not sure how all this would work on windows.

**Comment by erciccione** [comment]
I would keep it as simple as possible for now, since we only need to make a decent looking PDF and i don't plan anything more complex than that for the future. Let's avoid the change of template. I'm intalling pandoc and all needed dependencies right now so i can test (i'm on linux btw)

**Comment by erciccione** [comment]
Ok, i tested it using the command `pandoc --from markdown -o guide2.pdf monero-GUI-guide.md ` (since the format was kinda broken using `markdown_github`) but i'm not completely satisfated about it, the TOC is completely broken, but maybe it only needs some formatting.

**Comment by pazos** [comment]
hey, the toc, chapters, sections and subsections shall be generated by pandoc, not by hand. If you follow the convention of # chapter ## section ### subsection it should be easy to do. 

Look at this example which I generated:
[monero-GUI-guide.pdf](https://github.com/monero-ecosystem/monero-GUI-guide/files/1964472/monero-GUI-guide.pdf)

The only thing to do is handle external links in the last section.

**Comment by erciccione** [comment]
I understand that, but still looks quite ugly to me at the moment, in the example you posted there is even a blank page (page 20) in the middle of the document. It's true that it wasn't present in mine using the same tool, so it probably need just some tweaking here and there to look good. Right now i can't find the tool i used the first time (what i did was markdown ->html ->PDF) so i can't post an example. Don't get me wrong, i would love to use this if we can fix these two issues (blank parts and ugly external links at the bottom). Could you post an example with these two fixed?
Sorry if i didn't write clearly, i'm quite burned out at the moment.

**Comment by erciccione** [comment]
Hey @pazos i see you opened #26 , but i really think we don't need a template or a makefile here. PDFs will be generated probably 3-5 times a year, when doing so i can just do it manually. Let's keep the repo as clean as possible :)

Btw, i'm playing a bit with the various options here, i used your makefile as an example and  i helped myself with the official manual. I tweaked the commands a little bit and I came out with 

`pandoc --from markdown --variable urlcolor=blue -o guide.pdf monero-GUI-guide.md --toc --variable geometry:a4paper --dpi=200 --variable documentclass:report`

 the only differences are the depth of `--toc` (left default) and the `--dpi` variable to improve the quality of the pictures. What do you think? anyway i will give it a better look tomorrow with a properly working brain

>You are doing a great job with all the translation stuff and the ecosystem repo. Hands up +1

Thank you :)

**Comment by pazos** [comment]
> the only differences are the depth of --toc (left default) and the --dpi variable to improve the quality of the pictures. What do you think?

Yep, toc should be at least 3. DPI is a bit high (default is 96 afaik). 

> i really think we don't need a template or a makefile here. PDFs will be generated probably 3-5 times a year, when doing so i can just do it manually. Let's keep the repo as clean as possible :)

Ok, I will close the PR ;)

FYI you always use a template when using pandoc to "translate via latex" between markdown and pdf. In case you don't explicit use one you'll be using the default one, that can be viewed with `pandoc -D latex`. Command line will help with some basic stuff but some fine-tuning options like where to insert linebreaks are done modifying the template.

Feel free to ping me if you need some help with those rules

**Comment by erciccione** [comment]
@pazos I'm trying to build the PDF using pandoc but i don't understand why some pictures are misplaced. Any idea of how to fix this?

**Comment by pazos** [comment]
please give me more info. Missplaced how?. Also give me the command used to generate the pdf.

Are you running the command against this repo? If so I can try myself and see what is wrong.

**Comment by pazos** [comment]
mmm,  not sure if I can help without modyfing the template used by pandoc. Images are placed based on space available on pages.  The settings image is too large in height so it needs a page for itself. Latex see that is one page available after 14 so it places the image there.

There are too many ways of fixing this, but the most obvious is having each chapter on its own markdown and start each chapter on its own new page. So, in that case the Settings image will come first and then you'll have settings (1-18)

**Comment by erciccione** [comment]
Could you create a quick template i can use today to solve this?

**Comment by erciccione** [comment]
#56

**Comment by erciccione** [comment]
#56 is merged
