### ISSUE TITLE
Add information about GUI shortcuts

### ISSUE THREAD

**Issue by pazos** [monero-ecosystem/monero-GUI-guide#44]
On windows/linux
(ctrl+tab) -> go to the next page
(ctrl + shift + tab) ->go to the previous page

On osx:
(cmd+tab) -> go to the next page
(cmd + shift + tab) ->go to the previous page

For all OSes:

Press Ctrl to view each page shortcut. Press (ctrl+"shorcut") to go to that page

**Comment by erciccione** [comment]
forgot to say thanks for the suggestion @pazos :)

**Comment by Afron-Lysias** [comment]
On macOS:
(alt+tab) -> go to the next page
(alt+shift+tab) ->go to the previous page

cmd+tab on macOS is system's application switcher shortcut, equivalent to alt+tab on Windows.
