### ISSUE TITLE
The Spanish version needs to be updated

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/monero-GUI-guide#66]
Right now the section 6 it's obsolete and section 8.1 is missing. See [#55 (comment)](https://github.com/monero-ecosystem/monero-GUI-guide/pull/55#pullrequestreview-163027194)

**Comment by erciccione** [comment]
@blacklotus64 @lh1008

**Comment by BlackLotus64** [comment]
I'll be taking care of this, @lh1008 can help me to make a review :)

**Comment by erciccione** [comment]
#71

**Comment by erciccione** [comment]
#71 merged
