### ISSUE TITLE
Pandoc building missing translations to other languages

### ISSUE THREAD

**Issue by BlackLotus64** [monero-ecosystem/monero-GUI-guide#74]
When building in Pandoc to PDF (the only one I've tried until now) and to Spanish, there are some words that aren't translated to Spanish by default and it seems to be a thing build in Pandoc.

Those words are:

#**Contents:** it should be translated to *Contenido* in Spanish and to other word for other languages.
#**Chapters:** the chapters of the guide. It appears at the beginning of every chapter. 
#**Figure:** often used as *image* but still not translated. It appears below any image included in the guide.

Those are the words I noticed, and yes, of course it can be left that way and won't be a problem because many people are bilingual but to make a complete and more professional translation it must be correct to have everything correctly translated.

This will happen too for other languages, at least it's something we can predict but I'm not 100% sure.

**Comment by erciccione** [comment]
#78

**Comment by erciccione** [comment]
#78 is merged
