### ISSUE TITLE
[Proposal] Use markdown ordered lists

### ISSUE THREAD

**Issue by Rho-n** [monero-ecosystem/monero-GUI-guide#75]
The formatting for ordered instructions in the text, and when referencing certain numbered areas of an image, do not use markdown's ordered list formatting. Using it will allow for a better layout by pandoc when generating the various formats, and better control of how they look with CSS/LaTex.

Was there a decision not to use ordered lists?

**Comment by erciccione** [comment]
Yes, i agree it looks much better. I just didn't think about it back then.
Thank you for #76

**Comment by erciccione** [comment]
resolved by #76
